Repository TikkleSaver/BE, pull requests merged in 2025-05, with the labels that each got.

#2 [FEAT] 챌린지 생성하기 기능 구현. 멤버 임시 지정, 사진 기능X
  src/main/java/com/tikklesaver/domain/Category/repository/CategoryRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/controller/ChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/converter/ChallengeConverter.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/ChallengeRequestDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/ChallengeResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/entity/Challenge.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/ChallengeRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/service/ChallengeQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/ChallengeQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/member/repository/MemberRepository.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tikklesaver/global/apiPayload/exception/handler/ChallengeHandler.java
Labels: ✨ Feature

#10 [FEAT] 챌린지 가입하기 페이지 조회 api 구현
  src/main/java/com/tikklesaver/domain/Challenge/controller/ChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/converter/ChallengeConverter.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/ChallengeResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/entity/ChallengeScraped.java
  src/main/java/com/tikklesaver/domain/Challenge/entity/JoinChallenge.java
  src/main/java/com/tikklesaver/domain/Challenge/entity/MissionProof.java
  src/main/java/com/tikklesaver/domain/Challenge/entity/enums/Status.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/ChallengeScrapRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/JoinChallengeRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeCommandService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/ChallengeQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeQueryServiceImpl.java
Labels: ✨ Feature

#15 feat: s3 세팅 완료
  build.gradle
  src/main/java/com/tikklesaver/global/aws/s3/AmazonS3Manager.java
  src/main/java/com/tikklesaver/global/common/Uuid.java
  src/main/java/com/tikklesaver/global/config/AmazonConfig.java
  src/main/java/com/tikklesaver/global/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/tikklesaver/global/repository/UuidRepository.java
Labels: ✨ Feature, 🌏 Deploy, ⚙️ Setting

#16 feat: 챌린지 스크랩 patch api 구현
  src/main/java/com/tikklesaver/domain/Challenge/controller/ChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/controller/ChallengeScrapController.java
  src/main/java/com/tikklesaver/domain/Challenge/converter/ChallengeConverter.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/challenge/ChallengeRequestDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/challenge/ChallengeResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/challengeScrap/ChallengeScrapResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/entity/ChallengeScraped.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/ChallengeScrapRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeCommandService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/ChallengeScrap/ChallengeScrapCommandService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/ChallengeScrap/ChallengeScrapCommandServiceImpl.java
Labels: ✨ Feature

#17 [Refactor] 챌린지 생성 이미지 추가
  src/main/java/com/tikklesaver/domain/Challenge/controller/ChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeCommandService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeCommandServiceImpl.java
  src/main/java/com/tikklesaver/global/aws/s3/AmazonS3Manager.java
Labels: 🔨 Refactor

#19 [Refactor] 챌린지 신청 페이지 이미지 url 추가
  src/main/java/com/tikklesaver/domain/Challenge/converter/ChallengeConverter.java
Labels: 🔨 Refactor

#28 [FEAT] 지출 수정 API 구현
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseController.java
  src/main/java/com/tikklesaver/domain/Expense/converter/ExpenseConverter.java
  src/main/java/com/tikklesaver/domain/Expense/dto/ExpenseRequestDTO.java
  src/main/java/com/tikklesaver/domain/Expense/dto/ExpenseResponseDTO.java
  src/main/java/com/tikklesaver/domain/Expense/entity/Expense.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseCommandService.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseCommandServiceImpl.java
Labels: ✨ Feature

#31 [FEAT] 지출 조회 API 구현
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseController.java
  src/main/java/com/tikklesaver/domain/Expense/converter/ExpenseConverter.java
  src/main/java/com/tikklesaver/domain/Expense/dto/ExpenseResponseDTO.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryService.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryServiceImpl.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#30 [FEAT] 챌린지 가입 요청 api 구현
  src/main/java/com/tikklesaver/domain/Challenge/controller/ChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/controller/ChallengeScrapController.java
  src/main/java/com/tikklesaver/domain/Challenge/controller/JoinChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/converter/ChallengeConverter.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/challenge/ChallengeResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/joinChallenge/JoinChallengeResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/entity/JoinChallenge.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/JoinChallengeRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeCommandService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeCommandService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeQueryServiceImpl.java
Labels: ✨ Feature

#33 [Refactor] MyProduct를 Product와 합침
  src/main/java/com/tikklesaver/domain/product/converter/ProductConverter.java
  src/main/java/com/tikklesaver/domain/product/entity/MyProduct.java
  src/main/java/com/tikklesaver/domain/product/entity/Product.java
  src/main/java/com/tikklesaver/domain/wish/converter/WishConverter.java
  src/main/java/com/tikklesaver/domain/wish/entity/Wish.java
  src/main/java/com/tikklesaver/domain/wish/repository/WishRepositoryImpl.java
Labels: 🔨 Refactor

#34 [Feat] 나의 위시리스트 구매 완료 목록 조회 api 구현
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/converter/WishConverter.java
  src/main/java/com/tikklesaver/domain/wish/dto/WishResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/repository/WishRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/wish/repository/WishRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/WishQueryService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishQueryServiceImpl.java
Labels: ✨ Feature

#37 [FEAT] 지출 삭제 api 구현
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseController.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryService.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryServiceImpl.java
Labels: ✨ Feature

#40 [Feat] 존재하는 상품 위시 수정 api 구현
  src/main/java/com/tikklesaver/domain/product/entity/Product.java
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandService.java
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/dto/WishRequestDTO.java
  src/main/java/com/tikklesaver/domain/wish/entity/Wish.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandServiceImpl.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tikklesaver/global/apiPayload/exception/handler/WishHandler.java
Labels: ✨ Feature

#42 [Feat] 존재하는 상품 위시 삭제 api 구현
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandService.java
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandServiceImpl.java
Labels: ✨ Feature

#44 Feature/signup/#22
  build.gradle
  src/main/java/com/tikklesaver/domain/member/controller/MemberController.java
  src/main/java/com/tikklesaver/domain/member/converter/MemberConverter.java
  src/main/java/com/tikklesaver/domain/member/dto/CustomUserInfoDto.java
  src/main/java/com/tikklesaver/domain/member/dto/LoginRequestDto.java
  src/main/java/com/tikklesaver/domain/member/dto/MemberResponseDto.java
  src/main/java/com/tikklesaver/domain/member/dto/SignUpRequestDto.java
  src/main/java/com/tikklesaver/domain/member/entity/Member.java
  src/main/java/com/tikklesaver/domain/member/entity/MemberCategory.java
  src/main/java/com/tikklesaver/domain/member/entity/enums/MemberStatus.java
  src/main/java/com/tikklesaver/domain/member/repository/MemberRepository.java
  src/main/java/com/tikklesaver/domain/member/service/CustomUserDetailsService.java
  src/main/java/com/tikklesaver/domain/member/service/MemberCommandService.java
  src/main/java/com/tikklesaver/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/tikklesaver/global/annotation/CurrentMember.java
  src/main/java/com/tikklesaver/global/annotation/CurrentMemberArgumentResolver.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tikklesaver/global/apiPayload/exception/handler/JwtHandler.java
  src/main/java/com/tikklesaver/global/config/SecurityConfig.java
  src/main/java/com/tikklesaver/global/config/WebConfig.java
  src/main/java/com/tikklesaver/global/jwt/dto/JwtDto.java
  src/main/java/com/tikklesaver/global/jwt/filter/JwtAuthFilter.java
  src/main/java/com/tikklesaver/global/jwt/util/JwtUtil.java
Labels: ✨ Feature

#45 [Feat] 존재하지 않는 상품 위시 생성 api 구현
  src/main/java/com/tikklesaver/domain/product/converter/ProductConverter.java
  src/main/java/com/tikklesaver/domain/product/entity/Product.java
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandService.java
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/converter/WishConverter.java
  src/main/java/com/tikklesaver/domain/wish/dto/WishRequestDTO.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandServiceImpl.java
Labels: ✨ Feature

#47 [Feat] 존재하지 않던 상품 위시 수정 api 구현
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandService.java
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/converter/WishConverter.java
  src/main/java/com/tikklesaver/domain/wish/dto/WishRequestDTO.java
  src/main/java/com/tikklesaver/domain/wish/dto/WishResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandServiceImpl.java
Labels: ✨ Feature

#49 [Feat] 존재X 상품 (직접 추가) 위시 삭제 api 구현
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandService.java
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandServiceImpl.java
Labels: ✨ Feature

#51 [Feat] 위시 상세 조회 api 구현
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/dto/WishResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/repository/WishRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/wish/repository/WishRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/WishQueryService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishQueryServiceImpl.java
Labels: ✨ Feature

#53 [FEAT] 지출 목록 조회 API 구현
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseController.java
  src/main/java/com/tikklesaver/domain/Expense/converter/ExpenseConverter.java
  src/main/java/com/tikklesaver/domain/Expense/dto/ExpenseResponseDTO.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryService.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature

#59 [Feat] 나의 위시 공개/비공개 설정 api 구현
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandServiceImpl.java
Labels: ✨ Feature

#61 [Feat] 나의 위시 구매 상태 변경 api 구현
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandServiceImpl.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#63 [Feat] 위시 만족/불만족 설정 api 구현
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/WishCommandServiceImpl.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#72 [Refactor] contentType 추가
  src/main/java/com/tikklesaver/global/aws/s3/AmazonS3Manager.java
Labels: 🔨 Refactor

#73 [FEAT] 특정 사용자의 특정 달의 일별 지출 금액 조회 api 구현
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseController.java
  src/main/java/com/tikklesaver/domain/Expense/converter/ExpenseConverter.java
  src/main/java/com/tikklesaver/domain/Expense/dto/ExpenseResponseDTO.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryService.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryServiceImpl.java
Labels: ✨ Feature

#76 [FEAT] 지출 댓글 생성/수정/조회/삭제 api 구현
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseCommentController.java
  src/main/java/com/tikklesaver/domain/Expense/converter/ExpenseCommentConverter.java
  src/main/java/com/tikklesaver/domain/Expense/dto/ExpenseCommentRequestDTO.java
  src/main/java/com/tikklesaver/domain/Expense/dto/ExpenseCommentResponseDTO.java
  src/main/java/com/tikklesaver/domain/Expense/entity/ExpenseComment.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseCommentRepository.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseCommentRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseCommentRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseCommentCommandService.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseCommentCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseCommentQueryService.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseCommentQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/member/entity/Member.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tikklesaver/global/apiPayload/exception/handler/ExpenseCommentHandler.java
Labels: ✨ Feature

#77 [Feat] 위시 댓글 생성 api 구현
  src/main/java/com/tikklesaver/domain/wish/controller/WishCommentContoller.java
  src/main/java/com/tikklesaver/domain/wish/converter/WishCommentConverter.java
  src/main/java/com/tikklesaver/domain/wish/dto/wishComment/WishCommentRequestDTO.java
  src/main/java/com/tikklesaver/domain/wish/dto/wishComment/WishCommentResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/entity/Wish.java
  src/main/java/com/tikklesaver/domain/wish/repository/wishComment/WishCommentRepository.java
  src/main/java/com/tikklesaver/domain/wish/repository/wishComment/WishCommentRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/wish/repository/wishComment/WishCommentRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WIshCommentCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WishCommentCommandService.java
Labels: ✨ Feature

#79 [Feat] 위시 댓글 수정 api 구현
  src/main/java/com/tikklesaver/domain/wish/controller/WishCommentContoller.java
  src/main/java/com/tikklesaver/domain/wish/converter/WishCommentConverter.java
  src/main/java/com/tikklesaver/domain/wish/dto/wishComment/WishCommentRequestDTO.java
  src/main/java/com/tikklesaver/domain/wish/dto/wishComment/WishCommentResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/entity/WishComment.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WIshCommentCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WishCommentCommandService.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tikklesaver/global/apiPayload/exception/handler/WishCommentHandler.java
Labels: ✨ Feature

#86 Feature/onboarding/#57
  src/main/java/com/tikklesaver/domain/Challenge/repository/ChallengeRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/ChallengeScrapRepository.java
  src/main/java/com/tikklesaver/domain/member/controller/MemberController.java
  src/main/java/com/tikklesaver/domain/member/converter/MemberConverter.java
  src/main/java/com/tikklesaver/domain/member/dto/MemberRequestDto.java
  src/main/java/com/tikklesaver/domain/member/dto/MemberResponseDto.java
  src/main/java/com/tikklesaver/domain/member/entity/Member.java
  src/main/java/com/tikklesaver/domain/member/entity/MemberCategory.java
  src/main/java/com/tikklesaver/domain/member/repository/MemberCategoryRepository.java
  src/main/java/com/tikklesaver/domain/member/service/MemberCommandService.java
  src/main/java/com/tikklesaver/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepository.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tikklesaver/global/config/SecurityConfig.java
Labels: ✨ Feature

#95 [Refactor] 위시 관련 api JWT 토큰 연결
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandService.java
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/controller/VoteController.java
  src/main/java/com/tikklesaver/domain/wish/controller/WishCommentContoller.java
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/vote/VoteCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/vote/VoteCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishQueryService.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WIshCommentCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WishCommentCommandService.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WishCommentQueryService.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WishCommentQueryServiceImpl.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
Labels: 🔨 Refactor

#98 Feature/friend request/#87
  src/main/java/com/tikklesaver/domain/friend/controller/FriendController.java
  src/main/java/com/tikklesaver/domain/friend/entity/Friend.java
  src/main/java/com/tikklesaver/domain/friend/entity/FriendRequest.java
  src/main/java/com/tikklesaver/domain/friend/repository/FriendRepository.java
  src/main/java/com/tikklesaver/domain/friendRequest/controller/FriendRequestController.java
  src/main/java/com/tikklesaver/domain/friendRequest/converter/FriendReqConverter.java
  src/main/java/com/tikklesaver/domain/friendRequest/dto/FriendReqRequestDto.java
  src/main/java/com/tikklesaver/domain/friendRequest/dto/FriendReqResponseDto.java
  src/main/java/com/tikklesaver/domain/friendRequest/entity/FriendRequest.java
  src/main/java/com/tikklesaver/domain/friendRequest/entity/enums/RequestStatus.java
  src/main/java/com/tikklesaver/domain/friendRequest/repository/FriendReqRepository.java
  src/main/java/com/tikklesaver/domain/friendRequest/service/FriendRequestService.java
  src/main/java/com/tikklesaver/domain/friendRequest/service/FriendRequestServiceImpl.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/tikklesaver/global/apiPayload/exception/handler/FriendRequestHandler.java
Labels: ✨ Feature

#102 [FEAT] 챌린지 상세보기 페이지 api 구현
  src/main/java/com/tikklesaver/domain/Challenge/controller/JoinChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/controller/MissionProofController.java
  src/main/java/com/tikklesaver/domain/Challenge/converter/ChallengeConverter.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/challenge/ChallengeResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/missionProof/MissionProofRequestDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/missionProof/MissionProofResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/JoinChallengeRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/MissionProofRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/challenge/ChallengeRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/challenge/ChallengeRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/challenge/ChallengeRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/missionProof/MissionProofRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/missionProof/MissionProofRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/missionProof/MissionProofRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/ChallengeScrap/ChallengeScrapCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/MissionProof/MissionProofCommandServiceImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/MissionProof/MissionProofQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/MissionProof/MissionProofQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/member/service/MemberCommandServiceImpl.java
Labels: ✨ Feature

#109 [Feat] 친구 위시 구매 완료 목록 조희 api 구현
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/converter/WishConverter.java
  src/main/java/com/tikklesaver/domain/wish/dto/wish/WishResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishQueryService.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishQueryServiceImpl.java
Labels: ✨ Feature

#111 [Feat] 나와 친구 위시리스트 목록 조회 api 구현
  src/main/java/com/tikklesaver/domain/friend/repository/FriendRepository.java
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/converter/WishConverter.java
  src/main/java/com/tikklesaver/domain/wish/dto/wish/WishResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishQueryService.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishQueryServiceImpl.java
Labels: ✨ Feature

#113 [Feat] 나의 찬성 반대 투표 여부 조회 api 구현
  src/main/java/com/tikklesaver/domain/wish/controller/VoteController.java
  src/main/java/com/tikklesaver/domain/wish/converter/VoteConverter.java
  src/main/java/com/tikklesaver/domain/wish/dto/vote/VoteResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/service/vote/VoteQueryService.java
  src/main/java/com/tikklesaver/domain/wish/service/vote/VoteQueryServiceImpl.java
Labels: ✨ Feature

#122 [FEAT] 챌린지 가입 요청 수락, 거절 기능 구현
  src/main/java/com/tikklesaver/domain/Challenge/controller/JoinChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeCommandService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeCommandServiceImpl.java
  src/main/java/com/tikklesaver/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#124 [REFACTOR] 지출 달력 페이지 API 리팩토링
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseController.java
  src/main/java/com/tikklesaver/domain/member/controller/MemberController.java
Labels: 🔨 Refactor
