Repository TikkleSaver/BE, pull requests merged in 2025-06, with the labels that each got.

#130 [FEAT] 특정 사용자의 지출 목표 달성일 조회하는 API 구현
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseController.java
  src/main/java/com/tikklesaver/domain/Expense/converter/ExpenseConverter.java
  src/main/java/com/tikklesaver/domain/Expense/dto/ExpenseResponseDTO.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryService.java
  src/main/java/com/tikklesaver/domain/Expense/service/ExpenseQueryServiceImpl.java
Labels: ✨ Feature

#132 [REFACTOR] 지출 관련 api 연동 시 문제되는 디테일 수정
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseCommentController.java
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseController.java
  src/main/java/com/tikklesaver/domain/Expense/repository/ExpenseRepositoryImpl.java
Labels: 🔨 Refactor

#134 [Refac] 위시 내꺼인지 확인 추가
  src/main/java/com/tikklesaver/domain/wish/controller/WishCommentContoller.java
  src/main/java/com/tikklesaver/domain/wish/controller/WishController.java
  src/main/java/com/tikklesaver/domain/wish/converter/WishCommentConverter.java
  src/main/java/com/tikklesaver/domain/wish/dto/wish/WishResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/dto/wishComment/WishCommentResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishQueryService.java
  src/main/java/com/tikklesaver/domain/wish/service/wish/WishQueryServiceImpl.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WishCommentQueryService.java
  src/main/java/com/tikklesaver/domain/wish/service/wishComment/WishCommentQueryServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#136 [Refac] 참견소 위시 구매 여부 추가
  src/main/java/com/tikklesaver/domain/wish/dto/wish/WishResponseDTO.java
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryImpl.java
Labels: ✨ Feature, 🔨 Refactor

#138 [Refac] 위시 수정 제목, 브랜드 추가
  src/main/java/com/tikklesaver/domain/wish/dto/wish/WishRequestDTO.java
Labels: 🔨 Refactor

#139 [Refac] 빠진 제목/브랜드 추가
  src/main/java/com/tikklesaver/domain/product/service/ProductCommandServiceImpl.java
Labels: 🔨 Refactor

#141 [Refac] 불러오는 정보 값 순서 수정
  src/main/java/com/tikklesaver/domain/wish/repository/wish/WishRepositoryImpl.java
Labels: 🔨 Refactor

#145 [REFACTOR] 지출 관련 파라미터 name 설정
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseCommentController.java
  src/main/java/com/tikklesaver/domain/Expense/controller/ExpenseController.java
Labels: 🔨 Refactor

#151 [FIX] createdAt 오류 수정
  src/main/java/com/tikklesaver/domain/Challenge/converter/ChallengeConverter.java
Labels: 🐞 BugFix, 🔨 Refactor

#154 [FEAT]챌린저 참여 요청 수락 거절 구현
  src/main/java/com/tikklesaver/domain/Challenge/controller/JoinChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/converter/ChallengeConverter.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/challenge/ChallengeResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/JoinChallenge/JoinChallengeQueryServiceImpl.java
Labels: ✨ Feature

#159 [Remove] 불필요 파일 제거
  src/main/java/com/tikklesaver/global/validation/annotation/ExistTemp.java
  src/main/java/com/tikklesaver/global/validation/validator/TempExistValidator.java
Labels: ✨ Feature

#160 [FEAT] 인기 챌린지 top4 api 구현
  src/main/java/com/tikklesaver/domain/Challenge/controller/ChallengeController.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/challenge/ChallengeDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/challenge/ChallengeResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/joinChallenge/JoinChallengeDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/dto/joinChallenge/JoinChallengeResponseDTO.java
  src/main/java/com/tikklesaver/domain/Challenge/entity/Challenge.java
  src/main/java/com/tikklesaver/domain/Challenge/entity/JoinChallenge.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/challenge/ChallengeRepository.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/challenge/ChallengeRepositoryCustom.java
  src/main/java/com/tikklesaver/domain/Challenge/repository/challenge/ChallengeRepositoryImpl.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeQueryService.java
  src/main/java/com/tikklesaver/domain/Challenge/service/Challenge/ChallengeQueryServiceImpl.java
  src/main/java/com/tikklesaver/global/config/SecurityConfig.java
Labels: ✨ Feature
